# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('is_long', models.BooleanField(default=False)),
                ('url', models.URLField(verbose_name='http://www.swim-record.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.DecimalField(decimal_places=2, max_digits=7)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='swimrecord.Event')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='swimrecord.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='swimrecord.Team'),
        ),
        migrations.AddField(
            model_name='record',
            name='swimmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='swimrecord.Swimmer'),
        ),
    ]
